name: InspectCode

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  
jobs:
  inspection:
    runs-on: ubuntu-latest 
    name: Inspection
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup .NET
        id: setup-dotnet
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'
      - name: Restore
        run: dotnet restore App/App.sln
      - name: Inspect code
        uses: muno92/resharper_inspectcode@v1
        with:
          solutionPath: App/App.sln
          dotnetVersion: ${{ steps.setup-dotnet.outputs.dotnet-version }}
          minimumSeverity: WARNING
          minimumReportSeverity: WARNING
