name: Lint

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  lint-javascript:
    name: Lint JavaScript Codebase
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v4

      - name: Lint Codebase
        uses: jrcligny/run-eslint-action@v1
        with:
          pattern: 'App/Front/front/src/**/*.js'
          overrideConfigFile: App/Front/front/src/eslint.config.js
